---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: myom
spec:
  replicas: 1
  version: 4.4.12
  adminCredentials: ops-manager-admin-key 
  externalConnectivity:
    type: LoadBalancer
  applicationDatabase:
    members: 3
    version: 4.0.14-ent
...
